# k8s/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
stringData: # Using stringData means you don't have to base64 encode the password here
  mysql-root-password: "admin"
